# Generated by Django 5.2.4 on 2025-07-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='description',
        ),
    ]
